
package ioc.informaviescat.Vista;

import ioc.informaviescat.Controller.UserSaver;
import ioc.informaviescat.Controller.UsersManagement;
import ioc.informaviescat.Entities.User;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Pau Cors Bardolet
 */
public class guiLogin extends javax.swing.JFrame {

    ImageIcon img = new ImageIcon("ICONS/icon.png");
    /**
     * Creates new form guiLogin
     */
    public guiLogin() {
        initComponents();
        
        //Recupera usuari i contrasenya guardats.
        String[] credentials = UserSaver.restoreCredentials();
        textUser.setText(credentials[0]);
        textPassword.setText(credentials[1]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textUser = new javax.swing.JTextField();
        checkSaveUser = new javax.swing.JCheckBox();
        botoEntrar = new javax.swing.JButton();
        textPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informa Vies CAT");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Nom usuari:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Contrasenya:");

        checkSaveUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        checkSaveUser.setText("Guardar usuari");

        botoEntrar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botoEntrar.setText("Entrar");
        botoEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoEntrarActionPerformed(evt);
            }
        });

        textPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPasswordActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("src\\main\\java\\ioc\\informaviescat\\Pictures\\logo_screen.png"));
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 90, 260, 89);

        jLabel6.setIcon(new javax.swing.ImageIcon("src\\main\\java\\ioc\\informaviescat\\Pictures\\banner_resized.png"));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 330, 340, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon("src\\main\\java\\ioc\\informaviescat\\Pictures\\autopistes_editada_resized.jpg"));
        jLabel4.setAlignmentY(0.0F);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 400);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Benvingut/da");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkSaveUser)
                                .addGap(54, 54, 54)
                                .addComponent(botoEntrar))
                            .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(textUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(checkSaveUser))
                    .addComponent(botoEntrar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Defineix l'acció del botó Entrar
     *
     */
    private void botoEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoEntrarActionPerformed
        
        //Si s'escull la opció, guarda l'usuari i contrasenya.
        System.out.println("Guardar usuari: "+checkSaveUser.isSelected());
        if(checkSaveUser.isSelected()){
            UserSaver.saveCredentials(textUser.getText(), textPassword.getText());
        }
        else{
            UserSaver.saveCredentials("", "");
        }
            
        try{
            User usuari = UsersManagement.login(textUser.getText(), textPassword.getText());
            System.out.println("S'intenta loguejar l'usuari "+ textUser.getText()+" amb contrasenya "+textPassword.getText());
            System.out.println("    Nom: "+usuari.getName());
            System.out.println("    Cognoms: "+usuari.getLastName());
            System.out.println("    ID: "+usuari.getId());
            System.out.println("    Email: "+usuari.GetEmail());
            System.out.println("    Username: "+usuari.getUserName());
            
            if(usuari.getUserName().equals("")){
                Exception i = new Exception();
                throw i;
            }
            else{
                if(usuari.getRolId()==3){
                    UsersManagement.logout(usuari.getSessionId(), usuari.getId());
                    showMessageDialog(null, "Un usuari/a normal no pot fer servir l'aplicació d'escriptori");
                }
                else{
                    System.out.println("Ha arribat aquí");
                    MainScreen mainScreen = new MainScreen();
                    mainScreen.setLocationRelativeTo(null);
                    mainScreen.setIconImage(img.getImage());
                    System.out.println("Ha arribat aquí 2");
                    mainScreen.setSessionType(usuari);
                    System.out.println("Ha arribat aquí 3");
                    mainScreen.setVisible(true);

                    this.dispose();
                }
            }
        } catch (Exception e) {
            showMessageDialog(null, "Problema amb la connexió");
        }
    }//GEN-LAST:event_botoEntrarActionPerformed

    /**
     * Quan s'apreta enter al escriure la contrasenya, també intenta fer login
     *
     */
    private void textPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPasswordActionPerformed
        System.out.println("Guardar usuari: "+checkSaveUser.isSelected());
        if(checkSaveUser.isSelected()){
            UserSaver.saveCredentials(textUser.getText(), textPassword.getText());
        }
        else{
            UserSaver.saveCredentials("", "");
        }
            
        try{
            User usuari = UsersManagement.login(textUser.getText(), textPassword.getText());
            System.out.println("S'intenta loguejar l'usuari "+ textUser.getText()+" amb contrasenya "+textPassword.getText());
            System.out.println("    Nom: "+usuari.getName());
            System.out.println("    Cognoms: "+usuari.getLastName());
            System.out.println("    ID: "+usuari.getId());
            System.out.println("    Email: "+usuari.GetEmail());
            System.out.println("    Username: "+usuari.getUserName());
            
            if(usuari.getUserName().equals("")){
                Exception i = new Exception();
                throw i;
            }
            else{
                if(usuari.getRolId()==3){
                    UsersManagement.logout(usuari.getSessionId(), usuari.getId());
                    showMessageDialog(null, "Un usuari/a normal no pot fer servir l'aplicació d'escriptori");
                }
                else{
                    System.out.println("Ha arribat aquí");
                    MainScreen mainScreen = new MainScreen();
                    mainScreen.setLocationRelativeTo(null);
                    mainScreen.setIconImage(img.getImage());
                    System.out.println("Ha arribat aquí 2");
                    mainScreen.setSessionType(usuari);
                    System.out.println("Ha arribat aquí 3");
                    mainScreen.setVisible(true);

                    this.dispose();
                }
            }
            
            
        } catch (Exception e) {
            showMessageDialog(null, "Problema amb la connexió");
        }
    }//GEN-LAST:event_textPasswordActionPerformed

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoEntrar;
    private javax.swing.JCheckBox checkSaveUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField textPassword;
    private javax.swing.JTextField textUser;
    // End of variables declaration//GEN-END:variables
}
